name: flutter_dev_toolkit_example
description: Example app for Flutter Dev Toolkit
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  flutter_dev_toolkit:
    path: ../

flutter:
  uses-material-design: true
