name: flutter_dev_toolkit
description: "A powerful, modular in-app developer console for Flutter apps. Includes logs, network inspector, route tracker, performance tools, and plugin system."
version: 1.1.0
homepage: https://github.com/aayushkedawat/flutter_dev_toolkit
repository: https://github.com/aayushkedawat/flutter_dev_toolkit
issue_tracker: https://github.com/aayushkedawat/flutter_dev_toolkit/issues
documentation: https://github.com/aayushkedawat/flutter_dev_toolkit#readme


environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  dio:
  flutter:
    sdk: flutter
  flutter_bloc:
  bloc:
  http:
  share_plus:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
topics:
  - debug
  - logger
  - network
  - app-state observer
  - bloc observer
  - developer-tools
  - flutter