name: flutter_dev_toolkit
description: "A powerful, modular in-app developer console for Flutter apps. Includes logs, network inspector, route tracker, performance tools, and plugin system."
version: 1.0.0
homepage: https://github.com/aayushkedawat/flutter_dev_toolkit
repository: https://github.com/aayushkedawat/flutter_dev_toolkit
issue_tracker: https://github.com/aayushkedawat/flutter_dev_toolkit/issues
documentation: https://github.com/aayushkedawat/flutter_dev_toolkit#readme


environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  http: ^1.4.0
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
topics:
  - debug
  - logger
  - network
  - developer-tools
  - flutter