name: flutter_dev_toolkit
description: "A powerful, modular in-app developer console for Flutter apps. Includes logs, network inspector, route tracker, performance tools, and plugin system."
version: 1.1.2
homepage: https://github.com/aayushkedawat/flutter_dev_toolkit
repository: https://github.com/aayushkedawat/flutter_dev_toolkit
issue_tracker: https://github.com/aayushkedawat/flutter_dev_toolkit/issues
documentation: https://github.com/aayushkedawat/flutter_dev_toolkit#readme


environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  dio: ">=5.2.0 <6.0.0"
  flutter:
    sdk: flutter
  flutter_bloc: ">=8.0.0 <10.0.0"
  bloc: ">=8.0.0 <10.0.0"
  http: ">=0.13.0 <2.0.0"
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
topics:
  - debug
  - logger
  - network
  - developer-tools
  - flutter
screenshots:
  - path: screenshots/logs.png
    description: "Log console showing real-time filtered logs with colored severity levels."
  - path: screenshots/actions.png
    description: "Actions tab with options to export and clear logs and route data."
  - path: screenshots/bloc_inspector_details.png
    description: "Detailed view of a selected Bloc state change in the App State Inspector."
  - path: screenshots/bloc_inspector.png
    description: "App State Inspector showing a list of recent Bloc state transitions."
  - path: screenshots/device_info.png
    description: "Device Info plugin displaying hardware and OS specifications."
  - path: screenshots/network_details_error.png
    description: "Network inspector displaying error response details of an API call."
  - path: screenshots/network_details_request.png
    description: "Request tab showing headers, parameters, and payload of the API request."
  - path: screenshots/network_details_response.png
    description: "Response tab displaying the parsed JSON body of the API response."
  - path: screenshots/network_interceptor.png
    description: "List of captured network calls with filter and replay support."
  - path: screenshots/route.png
    description: "Route tab showing navigation stack and screen transition durations."
